title: JivaFlow Blog
description: Backend, Algorithms, and mindful tech
author: JivaFlow
email: contact@yourdomain.dev
url: https://username.github.io
theme: minima
timezone: Asia/Seoul
# GitHub Pages는 기본적으로 미래 날짜 포스트를 숨깁니다. 필요시 true로.
future: false

nav_links:
  - title: "Home"
    url: "/"
  - title: "Algorithm"
    url: "/categories/algorithm/"
  - title: "Spring Boot"
    url: "/categories/springboot/"