title: JivaFlow Blog
description: Backend, Algorithms, and mindful tech
author: JivaFlow
email: contact@yourdomain.dev
url: https://username.github.io  # 커스텀 도메인 연결시 변경
theme: minima

nav_links:
  - title: "Home"
    url: "/"
  - title: "Algorithm"
    url: "/categories/algorithm/"
  - title: "Spring Boot"
    url: "/categories/springboot/"