title: JivaFlow Blog
description: Backend, Algorithms, and mindful tech
author: JivaFlow
email: contact@yourdomain.dev
url: https://username.github.io
theme: minima
timezone: Asia/Seoul
future: false

nav_links:
  - title: "Home"
    url: "/"
  - title: "Algorithm"
    url: "/categories/algorithm/"
  - title: "Spring Boot"
    url: "/categories/springboot/"
  - title: "Search"
    url: "/search/"